services:
  db:
    image: postgres:16-alpine
    container_name: rcmoocs_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: rcmoocs_lms
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432"
    volumes:
      - lms_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rcmoocs-net

  migration:
    build:
      context: .
      dockerfile: scripts/Dockerfile.migrate
    container_name: rcmoocs-migrations
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - rcmoocs-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rcmoocs_lmsapp
    restart: always
    ports:
      - "5003:5000"
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - rcmoocs-net

volumes:
  lms_postgres_data:

networks:
  rcmoocs-net:
    driver: bridge