apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmsapp-deploy
  namespace: lmsapp
  labels:
    app: lmsapp-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lmsapp-web
  template:
    metadata:
      labels:
        app: lmsapp-web
    spec:
      containers:
      - name: lmsapp-web
        image: manishvishwa801/lms-web:latest
        ports:
        - containerPort: 5002